[2020-06-05 21:09:30,020] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: ml_pipeline.serve 2020-06-05T20:55:29.312218+00:00 [queued]>
[2020-06-05 21:09:30,033] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: ml_pipeline.serve 2020-06-05T20:55:29.312218+00:00 [queued]>
[2020-06-05 21:09:30,033] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 21:09:30,033] {taskinstance.py:880} INFO - Starting attempt 2 of 4
[2020-06-05 21:09:30,033] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 21:09:30,042] {taskinstance.py:900} INFO - Executing <Task(BashOperator): serve> on 2020-06-05T20:55:29.312218+00:00
[2020-06-05 21:09:30,045] {standard_task_runner.py:53} INFO - Started process 26622 to run task
[2020-06-05 21:09:30,096] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: ml_pipeline.serve 2020-06-05T20:55:29.312218+00:00 [running]> airflow.us-central1-a.c.greenr-276821.internal
[2020-06-05 21:09:30,108] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-05 21:09:30,109] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpo274ds8w/servelmtawomn
[2020-06-05 21:09:30,110] {bash_operator.py:115} INFO - Running command: python3 /home/binhphansamsung/airflow/scripts/serve.py serve
[2020-06-05 21:09:30,117] {bash_operator.py:122} INFO - Output:
[2020-06-05 21:09:32,730] {bash_operator.py:126} INFO - INFO:     Started server process [26624]
[2020-06-05 21:09:32,730] {bash_operator.py:126} INFO - INFO:     Waiting for application startup.
[2020-06-05 21:09:32,730] {bash_operator.py:126} INFO - INFO:     Application startup complete.
[2020-06-05 21:09:32,731] {bash_operator.py:126} INFO - ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8008): address already in use
[2020-06-05 21:09:32,731] {bash_operator.py:126} INFO - INFO:     Waiting for application shutdown.
[2020-06-05 21:09:32,731] {bash_operator.py:126} INFO - INFO:     Application shutdown complete.
[2020-06-05 21:09:33,107] {bash_operator.py:130} INFO - Command exited with return code 1
[2020-06-05 21:09:33,114] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-06-05 21:09:33,116] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-05 21:09:40,009] {logging_mixin.py:112} INFO - [2020-06-05 21:09:40,009] {local_task_job.py:103} INFO - Task exited with return code 1
