[2020-06-05 21:12:10,749] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: ml_pipeline.serve 2020-06-05T20:55:29.312218+00:00 [queued]>
[2020-06-05 21:12:10,758] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: ml_pipeline.serve 2020-06-05T20:55:29.312218+00:00 [queued]>
[2020-06-05 21:12:10,758] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 21:12:10,758] {taskinstance.py:880} INFO - Starting attempt 3 of 4
[2020-06-05 21:12:10,758] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 21:12:10,767] {taskinstance.py:900} INFO - Executing <Task(BashOperator): serve> on 2020-06-05T20:55:29.312218+00:00
[2020-06-05 21:12:10,770] {standard_task_runner.py:53} INFO - Started process 26852 to run task
[2020-06-05 21:12:10,820] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: ml_pipeline.serve 2020-06-05T20:55:29.312218+00:00 [running]> airflow.us-central1-a.c.greenr-276821.internal
[2020-06-05 21:12:10,832] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-05 21:12:10,833] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpmgjw004m/servewb93agah
[2020-06-05 21:12:10,833] {bash_operator.py:115} INFO - Running command: python3 /home/binhphansamsung/airflow/scripts/serve.py serve
[2020-06-05 21:12:10,840] {bash_operator.py:122} INFO - Output:
[2020-06-05 21:12:13,270] {bash_operator.py:126} INFO - INFO:     Started server process [26854]
[2020-06-05 21:12:13,270] {bash_operator.py:126} INFO - INFO:     Waiting for application startup.
[2020-06-05 21:12:13,270] {bash_operator.py:126} INFO - INFO:     Application startup complete.
[2020-06-05 21:12:13,271] {bash_operator.py:126} INFO - ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8008): address already in use
[2020-06-05 21:12:13,271] {bash_operator.py:126} INFO - INFO:     Waiting for application shutdown.
[2020-06-05 21:12:13,271] {bash_operator.py:126} INFO - INFO:     Application shutdown complete.
[2020-06-05 21:12:13,651] {bash_operator.py:130} INFO - Command exited with return code 1
[2020-06-05 21:12:13,659] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-06-05 21:12:13,660] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-05 21:12:20,744] {logging_mixin.py:112} INFO - [2020-06-05 21:12:20,744] {local_task_job.py:103} INFO - Task exited with return code 1
